# NumPy

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/logo.png" width=150>

在本课中，我们将学习使用NumPy包进行数值分析的基础知识。

<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/numpy.png" width=300>




# NumPy 基础知识

In [1]:
import numpy as np

In [2]:
# 使得多次生成的随机数相同
np.random.seed(seed=1234)

In [3]:
# 标量（scalars）
x = np.array(6) # scalar
print ("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [4]:
# 一维数组（array）
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [ ]:
# 三维数组（矩阵（matrix））
x = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print ("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
x ndim:  3
x shape: (1, 3, 3)
x size:  9
x dtype:  int64


In [5]:
# 函数
print ("np.zeros((2,2)):\n", np.zeros((2,2)))
print ("np.ones((2,2)):\n", np.ones((2,2)))
print ("np.eye((5)):\n", np.eye((5)))
print ("np.random.random((2,2)):\n", np.random.random((2,2)))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((5)):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
np.random.random((2,2)):
 [[0.19151945 0.62210877]
 [0.43772774 0.78535858]]


In [6]:
import numpy as np

# Generate a random float between 0 and 1
random_float = np.random.rand()
print(random_float)

0.7799758081188035


In [7]:
# Create a 2x3 array of random floats between 0 and 1
random_array = np.random.rand(2, 3)
print(random_array)

[[0.27259261 0.27646426 0.80187218]
 [0.95813935 0.87593263 0.35781727]]


In [9]:
# Generate a random integer between 1 and 10
random_int = np.random.randint(1, 100)
print(random_int)

93


In [10]:
# Shuffle an array
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)

[4 5 3 2 1]


In [11]:
# Draw 5 samples from a normal distribution with mean 0 and standard deviation 1
samples = np.random.normal(0, 1, 5)
print(samples)

[ 0.1458091   2.89409095 -0.30426018  0.861661   -0.68992667]


# 索引

In [12]:
# 索引（indexing）
x = np.array([1, 2, 3])
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x[0]:  1
x:  [0 2 3]


In [13]:
# 切片（slicing）
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1])
print ("x row 0: ", x[0, :])
print ("x rows 0,1,2 & cols 1,2: \n", x[:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1,2 & cols 1,2: 
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [15]:
# 整数数组索引
print(x)

print(len(x))
rows_to_get = np.arange(len(x))
print ("rows_to_get: ", rows_to_get)

cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)

print ("indexed values: ", x[rows_to_get, cols_to_get])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [17]:
# 布尔数组索引
x = np.array([[1,2], [3, 4], [5, 6]])
print ("x:\n", x)

print ("x > 2:\n", x > 2)

print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# 数组基础知识

In [19]:
# 数学基础
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)

print("x:\n", x)
print("y:\n", y)

print ("x + y:\n", np.add(x, y)) # or x + y

print ("x - y:\n", np.subtract(x, y)) # or x - y

print ("x * y:\n", np.multiply(x, y)) # or x * y

x:
 [[1. 2.]
 [3. 4.]]
y:
 [[1. 2.]
 [3. 4.]]
x + y:
 [[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


<img src="https://raw.githubusercontent.com/LisonEvf/practicalAI-cn/master/images/matrix.png" width=400>


In [22]:
# 点积
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # 我们可以指定dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)

print("a:\n", a)
print("b:\n", b)

print(a.dot(b))

a:
 [[1. 2. 3.]
 [4. 5. 6.]]
b:
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
[[ 58.  64.]
 [139. 154.]]


In [23]:
# 跨维度求和
x = np.array([[1,2],[3,4]])
print (x)
print ("sum all: ", np.sum(x)) # 将所有元素相加
print ("sum by col: ", np.sum(x, axis=0)) # 逐列将元素相加
print ("sum by row: ", np.sum(x, axis=1)) # 逐行将元素相加

[[1 2]
 [3 4]]
sum all:  10
sum by col:  [4 6]
sum by row:  [3 7]


In [24]:
# 转置
print ("x:\n", x)
print ("x.T:\n", x.T)

x:
 [[1 2]
 [3 4]]
x.T:
 [[1 3]
 [2 4]]


# 数组高级知识

In [31]:
# np.tile：重复维度
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])

print(len(x))

addent = np.tile(y, (len(x), 1))
# addent = np.tile(y, len(x))
print ("addent: \n", addent)

z = x + addent
print ("z:\n", z)

2
addent: 
 [[5 6]
 [5 6]]
z:
 [[ 6  8]
 [ 8 10]]


In [32]:
# 广播（broadcasting）
x = np.array([[1,2], [3,4]])
y = np.array([5, 6])
z = x + y
print ("z:\n", z)

z:
 [[ 6  8]
 [ 8 10]]


In [33]:
# 改变维度
x = np.array([[1,2], [3,4], [5,6]])
print (x)
print ("x.shape: ", x.shape)
y = np.reshape(x, (2, 3))
print ("y.shape: ", y.shape)
print ("y: \n", y)

[[1 2]
 [3 4]
 [5 6]]
x.shape:  (3, 2)
y.shape:  (2, 3)
y: 
 [[1 2 3]
 [4 5 6]]


In [51]:
# 删除维度
x = np.array([[[1,2,1]],[[2,2,3]]])
# x = np.array([[[[1,2,1],[2,2,3]]]])
print ("x.shape: ", x.shape)
y = np.squeeze(x, axis=1) # 删除维度1
print ("y.shape: ", y.shape)
print ("y: \n", y)

x.shape:  (2, 1, 3)
y.shape:  (2, 3)
y: 
 [[1 2 1]
 [2 2 3]]


In [53]:
# 添加维度
x = np.array([[1,2,1],[2,2,3]])
print ("x.shape: ", x.shape)
y = np.expand_dims(x, 1) # 扩展维度1
print ("y.shape: ", y.shape)
print ("y: \n", y)

x.shape:  (2, 3)
y.shape:  (2, 1, 3)
y: 
 [[[1 2 1]]

 [[2 2 3]]]


# 其它资源

你不必熟悉本文中任何东西，因为我们将在后面的课程中仔细研究NumPy。如果你对Numpy感到好奇，可以自行查看 [NumPy reference manual](https://docs.scipy.org/doc/numpy-1.15.1/reference/).